#该文件中配置红包服务的测试环境配置数据
red:
  remark: '{cipher}AQBzDO5I27FEE09KDAoyFJaVexU9SDQW68eqAjoHwhbPo41RF5OmtMmgjCwIjd7jvjqiqOcmKLJjKaAhc2uLS6/0crv4P6cG7KcQlc5bbUwQQ5NasyvZFIGdwdwUsVYb52qZYfh3zsUnOJQtueXS1tPHGSVy5A9XuDhj4XeUsLLkaavuCHUkR2VySi0JvRXZWvjmxn8FxtyCM73JgfeP0v75gmgZSuGqN/CHQnZEKMsGHL//b+e9TdEJdRC/tjtlcARBTtF+E5Ck0tRrJVyKSiHgDnPsJCVPAk97Og+5lFCrG/IA5ECSUHgc7sDzpOtDRs8Ee/5wSuJ443++zUH7HrPHTHS+GdOYFnXFSvfiY5ze0OP90AMR8LxxgUpIsj86VCa0qKce57lY70dCGkeOHtod'
